### ISSUE TITLE
Initial run on Maven project results in annotation directory not found error

### ISSUE THREAD

**Issue by snowe2010** [mjedynak/pit-idea-plugin#13]
Trying to get this set up for the first time and I'm getting a `Error: java: directory not found: /target/generated-sources/annotations` error. I don't see where to specify this in the configuration.

**Comment by snowe2010** [comment]
![image](https://cloud.githubusercontent.com/assets/1534535/17146518/1130634a-531c-11e6-86aa-dde0589aa4da.png)

**Comment by mjedynak** [comment]
If you provide sample project that reproduces the issue, I'll reopen and try to fix.
