### ISSUE TITLE
No default JUnit 5 support

### ISSUE THREAD

**Issue by keetron** [mjedynak/pit-idea-plugin#21]
We use Junit 5 and when running the plugin I get this error:
`9:25:22 AM PIT >> INFO : MINION : 9:25:22 AM PIT >> SEVERE : JUnit was not found on the classpath. PIT requires JUnit 4.6 or above.`

I know that to be able to use JUnit 5 I have to apply an additional plugin to pitest 1.4.2 so everything works fine commandline.

I can make a PR to refine the above  error message?

**Comment by kiview** [comment]
Plugin is not working for me with JUnit5 tests. Maven with JUnit5 Plugin works fine.

**Comment by goerge** [comment]
@keetron Could you elaborate on how you worked around the issue? Thanks

**Comment by keetron** [comment]
To be honest, this is so long ago , I would have no idea. I no longer work at this place anymore so I cannot check the codebase either.
