### ISSUE TITLE
CreateProcess error=206

### ISSUE THREAD

**Issue by pvsehgal** [mjedynak/pit-idea-plugin#31]
When running the mutation runner I receive the following error:

Cannot run prgram "C:\Program Files\Java\jdk1.8.0_162\bin\java.exe": CreateProcess error=206, The filename or extension is too long

![image](https://user-images.githubusercontent.com/12019833/53511271-f5df7780-3ab7-11e9-9a32-58aac7055605.png)

**Comment by d215steinberg** [comment]
This is a re-opening of https://github.com/mjedynak/pit-idea-plugin/issues/18, which was only partially fixed (if at all) in 1.4.0.

**Comment by Bozo5548** [comment]
I have the same issue.
Looks like it's resolved in PIT version 1.4.6
https://github.com/szpak/gradle-pitest-plugin/issues/92

**Comment by mjedynak** [comment]
fixed in [1.4.3](https://github.com/mjedynak/pit-idea-plugin/releases/tag/1.4.3)
