### ISSUE TITLE
Default Junit5 Support

### ISSUE THREAD

**Issue by smfaizalkhan** [mjedynak/pit-idea-plugin#34]
Thanks for the plugin for idea.
As of now for junit5 as per  the official document ,we need to add the plugin dependency in pom
[Junit5](https://github.com/pitest/pitest-junit5-plugin)
which works fine

But i dint want as part of pom ,rather use personally from the idea. plugin ,so when i tried to run it ,i got the same error as stated in the below ticket.

     PIT >> SEVERE : Error generating coverage. Please check that your classpath contains JUnit 
       4.6 or above.

As i cannot reopen the below issue, so not a duplicate 
https://github.com/mjedynak/pit-idea-plugin/issues/21

Regards,
Faizal

**Comment by adriana-lazar** [comment]
Looking forward to having this available! It is in my pom now as well :(

**Comment by SR-Lut3t1um** [comment]
#38 I created a PR containing the dependency.

**Comment by mjedynak** [comment]
implemented in 1.4.4
