### ISSUE TITLE
Please upgrade to pitest-junit5-plugin version 0.15.0 so that junit 5.8.0 is supported

### ISSUE THREAD

**Issue by spjoe** [mjedynak/pit-idea-plugin#53]
https://github.com/mjedynak/pit-idea-plugin/blob/11c8517bb2870f4e861e23357ec0eff3f9f83284/build.gradle#L32

**Comment by CidTori** [comment]
JUnit 5.7.2 needed here

**Comment by mjedynak** [comment]
fixed in 1.4.6
