### ISSUE TITLE
Bump-up Pitest-junit5-plugin version to support jUnit 5.9.1

### ISSUE THREAD

**Issue by Nahuel92** [mjedynak/pit-idea-plugin#57]
Hi there!
First of all, I have been using this plugin for a while and I want to thank you for this wonderful tool :)

Unfortunately, the plugin is not yet compatible with jUnit 5.9.1. This implies that tests annotated with `@ParameterizedTest` and `@MethodSource` are not working anymore.

That is why I would like to ask you to bump up the `pitest-junit5-plugin` to fix it as indicated in the [plugin repo](https://github.com/pitest/pitest-junit5-plugin/issues/69).

Best regards,
Nahuel

**Comment by Nahuel92** [comment]
Closing, as I developed my own plugin

**Comment by szpak** [comment]
@Nahuel92 You can put a link to it here.

**Comment by Nahuel92** [comment]
> @Nahuel92 You can put a link to it here.

Hey szpak!

Here's the link: https://github.com/Nahuel92/pit4u
