### ISSUE TITLE
Unable to specify the `--mutators` parameter

### ISSUE THREAD

**Issue by gillyobeast** [mjedynak/pit-idea-plugin#59]
Hi!

Glad to see this plugin, it's a useful tool to save us time on re-running/debugging our mutation tests, for which the full suite can take... a _while_ to run. :D 

However, in our project configuration, due to a PIT version upgrade changing the defaults, we set the `mutators` parameter to `OLD_DEFAULTS`. There is a plan to move to the 'new defaults' set of mutators, but for now it would be good to be able to set the `--mutators OLD_DEFAULTS` parameter in the run configuration for this plugin.

I've tried editing the default run configuration as below to specify the option:

<img width="640" alt="screenshot of IntelliJ's 'Run/Debug Configuration Templates' modal with 'PIT Runner' run config selected, highlighted in the 'other params' field is the text '--mutators OLD_DEFAULTS'" src="https://user-images.githubusercontent.com/17028440/227477027-7b8f1326-2646-422c-810e-6bdbc6bfbc23.png">

But when running from the project view, the command-line passed to Java doesn't add the `--mutators OLD_DEFAULTS` parameter, so the 'new defaults' set of mutators is run:
<img width="640" alt="screenshot of the 'PIT Runner' run configuration pane in IntelliJ, showing the command line passed to Java, with the default '--outputFormats' parameter but no '--mutators' parameter" src="https://user-images.githubusercontent.com/17028440/227478045-9a1ad8b0-2e4e-460a-87f9-3f7a530cbcf5.png">

After having run the run config, nothing is added to the 'Run Configurations' list in IntellIj to be able to edit it either - is there something I'm missing in that space?

Let me know if anything is unclear, and thanks for taking a look!

**Comment by mjedynak** [comment]
Hi, not sure why the params are not used in your case. 
The `OLD_DEFAULTS` was [removed ](https://github.com/hcoles/pitest/commit/c9b046285332b650c82f9d5d72d37af8adcf4c59#diff-e983408df63ab91fc55122de07a130697f925a62775a6a298369398a67387532L12) in 1.9.4, the latest version of the plugin is bundled with 1.9.5.

**Comment by gillyobeast** [comment]
Ah ok, I hadn't seen that. Thanks for letting me know about the removal of the `OLD_DEFAULTS`. 

I'll have another play with the plugin and see if replacing it with a set of mutators directly works, or if I can see anything else.
