### ISSUE TITLE
Be able to run pitests from the popup menu for a whole package / single file

### ISSUE THREAD

**Issue by neher** [mjedynak/pit-idea-plugin#6]
It would be nice if we have the same behavior as normal unit tests/coverage reports.

When you right click on a test file, you can run mutation tests only for that file.
When you right click on a package in project view, you can run mutation tests for all the unit tests in that package.

**Comment by JonasDralle** [comment]
**+1**
having PIT easily available would result in running PIT more often
![image](https://i.imgur.com/Nxmcyq8.png)
