### ISSUE TITLE
Message "pitest junit 5 plugin is not installed"

### ISSUE THREAD

**Issue by roefer** [mjedynak/pit-idea-plugin#61]
In the current version of the plugin, I have the problem that it reports

    JUnit 5 is on the classpath but the pitest junit 5 plugin is not installed

It turns out that the system class path contains `pitest-junit5-plugin-1.2.0.jar`, not `pitest-junit5-plugin-1.2.1.jar`. I have already uninstalled and reinstalled the plugin, but the problem remains.

**Comment by roefer** [comment]
It seems as if `ClassPathPopulator$_populateClassPathWithPitJar_closure1.class` adds `pitest-junit5-plugin-1.2.0.jar` to the class path.

**Comment by mjedynak** [comment]
Fixed in 1.4.10. I uploaded the version to Jetbrains Marketplace, should be publicly available soon.

**Comment by roefer** [comment]
Thanks!
